name: sylonow_user
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Routing
  go_router: ^14.2.0
  
  # Supabase
  supabase_flutter: ^2.9.1
  
  # Authentication
  google_sign_in: ^6.2.1
  
  # UI Components
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  lottie: ^3.0.0
  flutter_otp_text_field: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  smooth_page_indicator: ^1.1.0
  
  # Utils
  intl: ^0.19.0
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  
  # Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  ionicons: ^0.2.2
  
  # Animation
  animated_text_kit: ^4.2.2
  package_info_plus: ^8.0.0
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  permission_handler: ^12.0.0+1
  uuid: ^4.5.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.7
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # optional. default is 21

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/svgs/
    - assets/animations/
    
  fonts:
    - family: Okra
      fonts:
        - asset: assets/fonts/Okra-Regular.ttf
        - asset: assets/fonts/Okra-Medium.ttf
          weight: 500
        - asset: assets/fonts/Okra-MediumLight.ttf
          weight: 400
        - asset: assets/fonts/Okra-Bold.ttf
          weight: 700
        - asset: assets/fonts/Okra-ExtraBold.ttf
          weight: 800
